#!/usr/bin/env zsh
# 05-brewfile.sh — Install packages from ~/Brewfile

step "Brewfile Packages"

FILTERED="$HOME/.dotfiles/.brewfile-filtered"
SELECTOR="$HOME/.dotfiles/lib/brewfile-selector.sh"
INSTALL_BREWFILE="$HOME/Brewfile"

if [[ ! -f "$HOME/Brewfile" ]]; then
  fail "~/Brewfile not found"
  return 1
fi

if [[ -f "$FILTERED" ]]; then
  # Pre-generated by agentic install or previous selector run
  log "Using pre-filtered Brewfile: $FILTERED"
  INSTALL_BREWFILE="$FILTERED"
elif [[ -t 0 && -t 1 ]] && [[ -f "$SELECTOR" ]]; then
  # Interactive terminal — launch selector
  log "Launching interactive Brewfile selector..."
  zsh "$SELECTOR" "$HOME/Brewfile" "$FILTERED"
  if [[ $? -eq 0 && -f "$FILTERED" ]]; then
    INSTALL_BREWFILE="$FILTERED"
  else
    log "Selector cancelled or failed — using full Brewfile"
  fi
fi

spin "Installing Brewfile packages..." brew bundle --verbose --file="$INSTALL_BREWFILE" || {
  warn "brew bundle had partial failures (some casks may require manual install)"
}

spin "Cleaning up..." brew cleanup --verbose

# Clean up filtered file after install
if [[ -f "$FILTERED" ]]; then
  rm -f "$FILTERED"
  log "Cleaned up filtered Brewfile"
fi

ok "Brewfile packages installed"
