#!/usr/bin/env zsh
# 05-brewfile.sh — Install packages from ~/Brewfile

step "Brewfile Packages"

FILTERED="$HOME/.dotfiles/.brewfile-filtered"
MODE_FILTERED="$HOME/.dotfiles/.brewfile-mode-filtered"
SELECTOR="$HOME/.dotfiles/lib/brewfile-selector.sh"
SELECTOR_WINDOW="$HOME/.dotfiles/lib/brewfile-selector-window.sh"
BREWFILE_FILTER="$HOME/.dotfiles/lib/brewfile-filter.sh"
BOOTSTRAP_DIR="$HOME/.dotfiles/.bootstrap"
INSTALL_BREWFILE="$HOME/Brewfile"

if [[ ! -f "$HOME/Brewfile" ]]; then
  fail "~/Brewfile not found"
  return 1
fi

# ── Step 1: Filter Brewfile by machine type mode ────────────────────────
local current_mode
current_mode="$(get_install_mode)"
if is_dry_run; then
  log "[DRY RUN] Would filter Brewfile for mode: $current_mode"
elif [[ -f "$BREWFILE_FILTER" ]]; then
  log "Filtering Brewfile for mode: $current_mode"
  zsh "$BREWFILE_FILTER" "$current_mode" "$HOME/Brewfile" > "$MODE_FILTERED"
  INSTALL_BREWFILE="$MODE_FILTERED"
else
  warn "brewfile-filter.sh not found — using full Brewfile"
fi

# ── Step 2: Apply user selection (agentic pre-filter or interactive) ────
if is_dry_run; then
  if [[ -f "$FILTERED" ]]; then
    log "[DRY RUN] Would use pre-filtered Brewfile: $FILTERED"
  elif [[ -t 0 && -t 1 ]] && [[ -f "$SELECTOR" ]]; then
    log "[DRY RUN] Would launch interactive Brewfile selector (TTY available)"
  elif [[ -f "$SELECTOR" && -f "$SELECTOR_WINDOW" ]]; then
    log "[DRY RUN] Would open Brewfile selector in new Terminal window (non-TTY)"
  else
    log "[DRY RUN] Would use full Brewfile (no selector available)"
  fi
elif [[ -f "$FILTERED" ]]; then
  # Pre-generated by agentic install or previous selector run
  log "Using pre-filtered Brewfile: $FILTERED"
  INSTALL_BREWFILE="$FILTERED"
elif [[ "${DOTFILES_NONINTERACTIVE:-0}" == "1" ]]; then
  # Non-interactive mode — skip all selectors, use mode-filtered Brewfile
  log "Non-interactive mode — using mode-filtered Brewfile (no selector)"
elif [[ -t 0 && -t 1 ]] && [[ -f "$SELECTOR" ]]; then
  # Interactive terminal — launch selector
  log "Launching interactive Brewfile selector..."
  zsh "$SELECTOR" "$INSTALL_BREWFILE" "$FILTERED"
  if [[ $? -eq 0 && -f "$FILTERED" ]]; then
    INSTALL_BREWFILE="$FILTERED"
  else
    log "Selector cancelled or failed — using full Brewfile"
  fi
elif [[ -f "$SELECTOR" && -f "$SELECTOR_WINDOW" ]]; then
  # Non-TTY (agentic mode) — open selector in a new Terminal.app window
  log "No TTY available — opening Brewfile selector in new Terminal window..."

  mkdir -p "$BOOTSTRAP_DIR"

  # Clean stale marker files
  rm -f "$BOOTSTRAP_DIR/selector-done" \
        "$BOOTSTRAP_DIR/selector-failed" \
        "$BOOTSTRAP_DIR/selector-script.pid" \
        "$BOOTSTRAP_DIR/selector-window-id"

  # Open selector in a new Terminal.app window
  local window_id
  window_id=$(osascript <<APPLESCRIPT
tell application "Terminal"
  activate
  do script "exec zsh '${SELECTOR_WINDOW}' '${INSTALL_BREWFILE}' '${FILTERED}' '${BOOTSTRAP_DIR}'"
  return id of front window
end tell
APPLESCRIPT
  ) 2>/dev/null || {
    warn "Could not open Terminal.app window (headless environment?) — using full Brewfile"
    window_id=""
  }

  if [[ -n "$window_id" ]]; then
    echo "$window_id" > "$BOOTSTRAP_DIR/selector-window-id"
    log "Selector window opened (id=$window_id) — waiting for selection..."

    # Poll for completion markers (5-minute timeout)
    local elapsed=0
    local timeout=300
    local reminder_interval=30
    local next_reminder=$reminder_interval

    while (( elapsed < timeout )); do
      if [[ -f "$BOOTSTRAP_DIR/selector-done" ]]; then
        log "Selector completed successfully"
        break
      fi
      if [[ -f "$BOOTSTRAP_DIR/selector-failed" ]]; then
        log "Selector was cancelled or failed"
        break
      fi
      sleep 1
      elapsed=$((elapsed + 1))
      if (( elapsed >= next_reminder )); then
        log "Still waiting for Brewfile selection... (${elapsed}s elapsed)"
        next_reminder=$((next_reminder + reminder_interval))
      fi
    done

    if (( elapsed >= timeout )); then
      warn "Selector timed out after ${timeout}s"
    fi

    # Close the Terminal window
    if [[ -f "$BOOTSTRAP_DIR/selector-window-id" ]]; then
      local wid
      wid=$(< "$BOOTSTRAP_DIR/selector-window-id")
      osascript <<APPLESCRIPT 2>/dev/null || true
tell application "Terminal"
  repeat with w in windows
    if id of w is $wid then
      close w
      exit repeat
    end if
  end repeat
end tell
APPLESCRIPT
    fi

    # Clean up marker files
    rm -f "$BOOTSTRAP_DIR/selector-done" \
          "$BOOTSTRAP_DIR/selector-failed" \
          "$BOOTSTRAP_DIR/selector-script.pid" \
          "$BOOTSTRAP_DIR/selector-window-id"

    # Use filtered file if it was created
    if [[ -f "$FILTERED" ]]; then
      log "Using filtered Brewfile from selector"
      INSTALL_BREWFILE="$FILTERED"
    else
      warn "No filtered Brewfile produced — using full Brewfile"
    fi
  fi
fi

# Count expected packages from the Brewfile before running bundle
local expected_formulae expected_casks expected_total
expected_formulae=$(grep -cE '^\s*brew\s' "$INSTALL_BREWFILE" 2>/dev/null || echo 0)
expected_casks=$(grep -cE '^\s*cask\s' "$INSTALL_BREWFILE" 2>/dev/null || echo 0)
expected_total=$((expected_formulae + expected_casks))

local bundle_rc=0
spin "Installing Brewfile packages..." brew bundle --verbose --file="$INSTALL_BREWFILE" || bundle_rc=$?

# Count what actually got installed
local installed_formulae installed_casks installed_total
installed_formulae=$(brew list --formula 2>/dev/null | wc -l | tr -d ' ')
installed_casks=$(brew list --cask 2>/dev/null | wc -l | tr -d ' ')
installed_total=$((installed_formulae + installed_casks))

if (( bundle_rc != 0 )); then
  if (( installed_total == 0 && expected_total > 0 )); then
    # Total failure — zero packages installed
    fail "brew bundle failed — 0 of ${expected_total} expected packages installed"
    fail "Check network connectivity and retry: brew bundle --file=~/Brewfile"
    return 1
  elif (( expected_total > 0 )) && (( installed_total * 2 < expected_total )); then
    # Major failure — less than 50% installed
    warn "brew bundle had major failures — only ${installed_total} of ${expected_total} expected packages installed"
    warn "Retry failed packages: brew bundle --file=~/Brewfile"
  else
    # Partial failure — more than 50% installed
    warn "brew bundle had partial failures (${installed_total}/${expected_total} packages present — some casks may require manual install)"
  fi
fi

spin "Cleaning up..." brew cleanup --verbose

# Clean up filtered files after install
if [[ -f "$FILTERED" ]]; then
  rm -f "$FILTERED"
  log "Cleaned up filtered Brewfile"
fi
if [[ -f "$MODE_FILTERED" ]]; then
  rm -f "$MODE_FILTERED"
  log "Cleaned up mode-filtered Brewfile"
fi

if (( bundle_rc != 0 && installed_total == 0 && expected_total > 0 )); then
  fail "Brewfile packages FAILED — nothing was installed"
  return 1
fi

ok "Brewfile packages installed (${installed_total} formulae+casks)"
